### PR TITLE
Resolves #146, removes task runner (Grunt)

### LINKED ISSUE #146: Remove task runner (Grunt)
Task runner (Grunt, Gulp...) relies on plugins. This is good but also bad because only a few of them are actively maintained.

http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/

I think we should just use npm as a task runner and remove Grunt:

http://blog.teamtreehouse.com/use-npm-task-runner
http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

What do you think ?

### PR DESCRIPTION
**Pull request by Mogztter**
Resolves #146

### CODE REVIEW

**Comment by mojavelinux** [comment]
Wow, that's huge!! Nice work!

See ya Grunt! :stuck_out_tongue_winking_eye:

**Comment by mojavelinux** [comment]
I also appreciate that you updated the contributing guide. That's such an important part of the change.

**Comment by anthonny** [comment]
Really cool work, if you want i can make a review today :+1:

**Comment by Mogztter** [comment]
@anthonny Yes please, that would great

**Comment by Mogztter** [comment]
ATM the build is slower than Grunt. The minify task is taking more time but since we now have full control over the build process we can improve the code.

We could also fork/spawn child process but the debug will be harder so I don't know if it's worth it.

**Comment by Mogztter** [comment]
I switched to Google Closure Compiler and I added a release task:

```
$ DRY_RUN=1 npm run release 1.0.0
```
```
> asciidoctor.js@1.5.3-rc.1 release /home/guillaume/workspace/opensource/asciidoctor.js
> node npm/release.js "1.0.0"


Release version: 1.0.0
Dry run! To perform the release, run the command again without DRY_RUN environment variable
 - update package.json
 - update bower.json
 - git add -A .
 - git commit -m "Prepare version 1.0.0"
 - git tag 1.0.0
 - npm publish

To complete the release, you need to:
[ ] push changes upstream: 'git push origin master && git push origin 1.0.0'
[ ] publish a release page on GitHub: https://github.com/asciidoctor/asciidoctor.js/releases/new
[ ] create an issue here: https://github.com/webjars/asciidoctor.js to update Webjars
```

**Comment by mojavelinux** [comment]
> I added a release task

Hero! Let's shoot for automated releases across the board in 2016!

**Pull request merged**
