### PR TITLE
Rework the README

### LINKED ISSUE #69: Rework the README
I think the sections are not in the right order:

1. About
1. Installation
1. Usage
1. Contribute/Build from sources

It could also be nice to create a more detailed documentation about the Javascript API: the `Opal.hash2` is very confusing and there is a `$` before method name.

Another idea is to show how to create an extension in Javascript. I look at the code generated by Opal and it's quite straightforward...

### PR DESCRIPTION
**Pull request by Mogztter**
I split the `README` into two files:

 * `CONTRIBUTING.adoc`
 * `README.adoc`

I removed the part about "Using Asciidoctor and the native JavaScript environment from Ruby". I think it's an advanced topic, maybe we can add a wiki to explain how to do it ? Or a new file `GUIDE.adoc` ?
We also need to add a topic on how to write extension in JavaScript and how to build Asciidoctor options with `Opal.hash2`.

Resolves #69

### CODE REVIEW

**Comment by Mogztter** [comment]
@mojavelinux Maybe we can iterate on the README. That the first then we can consolidate/improve the documentation ? Or do you think we need to make some important changes first ?

**Comment by graphitefriction** [comment]
@mojavelinux @Mogztter So, what's the state of this pull request (are we waiting on a technical issue?) If the tech part is all good, I can review the content for clarity and usability -- then can we merge? And then I can mirror it on the website side :smiling_imp:

**Comment by Mogztter** [comment]
> So, what's the state of this pull request (are we waiting on a technical issue?) 

I don't know, I think we are just waiting a review on the content

> If the tech part is all good, I can review the content for clarity and usability

That would be great

> then can we merge? 

yes yes yes :smile:

**Comment by mojavelinux** [comment]
I _finally_ manage to write that intro. I sent a PR to the PR. I think the intro provides a warm welcome for contributors of all skill sets. I also threw some code of conduct language in there. Let me know what you think.

**Comment by mojavelinux** [comment]
Thank you @Mogztter for splitting up the files and getting it all setup.

**Comment by mojavelinux** [comment]
Excellent. I think we're good to merge!

**Comment by Mogztter** [comment]
@graphitefriction do you want to review the content for clarity and usability before merging ?

**Comment by mojavelinux** [comment]
@graphitefriction votes :+1:

**Comment by mojavelinux** [comment]
\o/

Note I've opened an issue to use this contributing guide in core as well. I've also raised the issue about adopting the Open Code of Conduct. See https://github.com/asciidoctor/asciidoctor/issues/1407

**Pull request merged**
