### PR TITLE
Write the Fedora package extension with the extension API

### PR DESCRIPTION
**Pull request by Mogztter**
@mojavelinux It was useful as I fixed two issues in the process :+1: 

The `$new` function fells a bit weird but I'm OK with it :wink: 

Reference: https://pagure.io/fedora-docs/docs-fp-o/blob/master/f/lib/extensions/package-inline-macro.js

### CODE REVIEW

**Comment by mojavelinux** [comment]
Oh, this is awesome!

I realized that it isn't necessary to create the processor instance when registering the extension. That's only required when the Antora context needs to be passed*. We'll have to think about how to handle that case, but since it isn't needed here, you can just pass the class itself.

\* In other words, we need some way to pass the Antora context to the processor when the extension is registered. One way is to create an instance of the processor when registering it.

**Comment by Mogztter** [comment]
> Oh, this is awesome!

:smile: 

> I realized that it isn't necessary to create the processor instance when registering the extension. 

That's true, you can pass a class.

```js
const registry = asciidoctor.Extensions.create();
registry.inlineMacro('package', asciidoctor.Extensions.createInlineMacroProcessor(/* ... */));
```

> That's only required when the Antora context needs to be passed*. We'll have to think about how to handle that case, but since it isn't needed here, you can just pass the class itself.

Indeed, in this case, the name of the inline macro is defined when calling the `inlineMacro` function.

> In other words, we need some way to pass the Antora context to the processor when the extension is registered. One way is to create an instance of the processor when registering it.

Yes you can "override" the initialize function to pass the Antora context:

```js
const PackageInlineMacro = asciidoctor.Extensions.createInlineMacroProcessor('PackageInlineMacro', {
  initialize: function (name, config, antoraContext) {
    this.antoraContext = antoraContext;
    this.super(name, config);
  },
  process: function (parent, target) {
    /* ... */
  }
});

PackageInlineMacro.$new('package', {}, Antora.getContext())
```

**Comment by mojavelinux** [comment]
> you can "override" the initialize function to pass the Antora context:

Indeed, that's what I've been doing. What I meant was some way to avoid the call to `$new`. Perhaps a createInstance method on the class that automatically passes the name and config, but accepts additional arguments.

**Comment by Mogztter** [comment]
> Indeed, that's what I've been doing. What I meant was some way to avoid the call to $new. Perhaps a createInstance (or create) method on the class that automatically passes the name and config, but accepts additional arguments.

Why not, I think we should track this improvement in a new issue right ?

**Comment by mojavelinux** [comment]
Indeed. Do you want me to file it? Or would you prefer to propose it?

**Comment by Mogztter** [comment]
Thanks!
@mojavelinux Otherwise does this pull request look good to you ? Can I merge as is ?

**Comment by mojavelinux** [comment]
Oh, absolutely. This looks extremely enticing!

**Pull request merged**
