### PR TITLE
WIP: JSDoc using Documentationjs

### PR DESCRIPTION
**Pull request by Mogztter**
[documentationjs](http://documentation.js.org/) is really nice!

```
npm install -g documentation
documentation build src/** -f html  -o build/docs
```

Open `build/docs/index.html`.

documentation

### CODE REVIEW

**Comment by ldez** [comment]
you can do that:
```shell
npm i -D documentation
```
in `package.json`:
```json
 // ...
  "scripts": {
    // ...
    "docs": "documentation build src/** -f html -o docs",
    "docs:lint": "documentation lint src/**"
  },
    // ...
```

Go to [Settings](https://github.com/asciidoctor/asciidoctor.js/settings), in the sections "GitHub Pages" choose "master branch /docs folder"

**Comment by Mogztter** [comment]
@ldez wooow thanks for the suggestion, I will try it 👍

**Comment by Mogztter** [comment]
I will merge this pull request just to get things started

**Comment by Mogztter** [comment]
http://asciidoctor.github.io/asciidoctor.js/index.html :tada:

**Comment by ldez** [comment]
Do not forget to put the link in the readme 😉

**Comment by ldez** [comment]
It's a really good news for asciidoctor.js users !!

**Comment by Mogztter** [comment]
A lot is still missing but I'm a big fan of the link between classes (ie. [Document#getDocumentTitle](http://asciidoctor.github.io/asciidoctor.js/#DocumentgetDocumentTitle) returns a [Document/Title](http://asciidoctor.github.io/asciidoctor.js/#documenttitle)).

You can explore the API ! And here's the link: https://github.com/asciidoctor/asciidoctor.js#javascript-api

**Comment by mojavelinux** [comment]
Great work! :tada:

**Comment by mojavelinux** [comment]
I think the link to the API docs should be a badge (similar to what we have for AsciidoctorJ).

**Comment by mojavelinux** [comment]
Before 1.5.6 is released, we need to add the wrappers for the remaining extension classes. Right now, we only have two of them (inlineMacro and block).

**Comment by Mogztter** [comment]
> I think the link to the API docs should be a badge (similar to what we have for AsciidoctorJ).

That's a good idea: https://img.shields.io/badge/jsdoc-master-blue.svg ?

**Comment by mojavelinux** [comment]
Looks great.

**Pull request merged**
