### PR TITLE
introduce CC_ANY character class

### PR DESCRIPTION
**Pull request by mojavelinux**
- define CC_ANY to match any character except a newline

This is related to https://github.com/asciidoctor/asciidoctor/issues/2783. We don't need to merge until the PR for that issue is ready to go in.

### CODE REVIEW

**Comment by Mogztter** [comment]
@mojavelinux It looks good to me, let me know when you want to merge

**Comment by mojavelinux** [comment]
Let's coordinate this for the 1.5.8 release. It shouldn't go in 1.5.7.

**Comment by mojavelinux** [comment]
The CC_MANY will no longer be required. And the CC_ANY is optional, though once Asciidoctor.js provides it, we can remove it from Asciidoctor Ruby.

**Comment by mojavelinux** [comment]
I recommend merging this as soon as Asciidoctor.js 1.5.7 is released.

**Comment by mojavelinux** [comment]
should I go ahead and remove this from asciidoctor/asciidoctor#master?

**Comment by Mogztter** [comment]
@mojavelinux yes please :+1:

**Pull request merged**
