### PR TITLE
Compile asciidoctor latex

### LINKED ISSUE #192: Asciidoctor-latex
Implement the asciidoctor-latex extension in asciidoctor.js.  I've implemented an alternative to using Ruby's prepend, so this should now be possible.  See [L571](https://github.com/asciidoctor/asciidoctor-latex/blob/master/lib/asciidoctor/latex/converter.rb#L571) of the converter code.  Code quality of `asciidoctor-latex` may need to be improved for this.

Reason: I would like be able to render asciidoc-latex documents in the client so as to avoid hitting the server so often for [scripta.io](http:www.scripta.io) and  [shoobox.io](http:www.shoobox.io). This will also set the stage for a better editor on these sites with a javascript frontend.

### PR DESCRIPTION
**Pull request by Mogztter**
Based on #182 

Resolves #192

### CODE REVIEW

**Comment by Mogztter** [comment]
@jxxcarlson Compilation is working fine but you need to make some changes in asciidoctor-latex:

 * [ ] Opal does not define a `__dir__` method, you need to replace [this line in latex.rb#L3](https://github.com/asciidoctor/asciidoctor-latex/blob/master/lib/asciidoctor/latex.rb#L3) with [something like asciidoctor.rb#L172](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L172)

**Comment by mojavelinux** [comment]
Wow! Pretty cool!

I'll follow up on the ThreadSafe issue. One workaround is to define ThreadSafe::Cache by mapping it to Hash in opal/ext.

**Comment by jxxcarlson** [comment]
Thanks so much!  Will get this done in the next day or two.

**Comment by Mogztter** [comment]
> One workaround is to define `ThreadSafe::Cache` by mapping it to Hash in opal/ext.

Good idea thanks!

**Comment by mojavelinux** [comment]
In fact, I'm almost wondering if that is the solution for asciidoctor/asciidoctor#1820. Either way, I will follow-up there.

**Comment by Mogztter** [comment]
In my opinion, your solution is simple enough to not make a special case in Asciidoctor core

**Comment by mojavelinux** [comment]
:+1:

**Pull request merged**
