### PR TITLE
Set max line length for uglify to 500

### PR DESCRIPTION
**Pull request by nawroth**
* Fixes usage in Safari, see https://github.com/asciidoctor/docgist/issues/27
* Makes debugging easier.
* The increase in file size is tiny.

### CODE REVIEW

**Comment by Mogztter** [comment]
@nawroth Thanks, do you know the max line length supported by Safari ?

**Comment by nawroth** [comment]
@Mogztter See https://github.com/asciidoctor/docgist/issues/27#issuecomment-167377931

**Comment by Mogztter** [comment]
@nawroth Ok and only 1Ko :smile:

**Comment by Mogztter** [comment]
And... merged :+1:

**Pull request merged**
