### PR TITLE
Upgrade Opal 1.2.0 (master)

### PR DESCRIPTION
**Pull request by ggrossetie**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Will this still work on Node.js 10? (I'm still deciding whether to drop Node.js 10 in Antora 3, or keep it for performance reasons).

**Comment by Mogztter** [comment]
> Will this still work on Node.js 10? (I'm still deciding whether to drop Node.js 10 in Antora 3, or keep it for performance reasons).

We won't actively test against Node.js 10 or 12 but it should still work.

**Comment by Mogztter** [comment]
Opal [v1.2.0.beta1](https://github.com/opal/opal/releases/tag/v1.2.0.beta1) is out!

**Comment by Mogztter** [comment]
Superseded by [#1106 ](https://github.com/asciidoctor/asciidoctor.js/pull/1359)

**Pull request closed without merging**
