### PR TITLE
Replace with escape code

### PR DESCRIPTION
**Pull request by Mogztter**
Ref: https://github.com/asciidoctor/asciidoctor.js/issues/314

At first I thought that the "Letter" category contained every other "Letter" categories but that's not true. For instance `\xDF` is defined in `P_Ll` (lowercase letter) but not in `P_L`... I don't know if this is intended or not...
As a consequence there's a lot of duplications. 

@mojavelinux Do you think it's worth to deduplicate ? I'm asking because it will be harder to resynchronize with https://github.com/slevithan/xregexp/blob/master/src/addons/unicode-categories.js (though I don't think this file will be update too often)

### CODE REVIEW

**Comment by mojavelinux** [comment]
Great! I'll have a look asap.

**Comment by mojavelinux** [comment]
> At first I thought that the "Letter" category contained every other "Letter" categories but that's not true.

This confused me as well.

> As a consequence there's a lot of duplications.

This was my main concern. I really would like to make it as small as possible. I think the key here is to keep the script that generates it handy. That way, when we need to update for whatever reason, we just refine the script. And we can continue to make improvements to what it outputs as we find things we missed. In other words, we really need to automate this.

**Comment by mojavelinux** [comment]
Here's the script I used to condense the character references.

```rb
require 'js_regex'
require 'strscan'

CHAR_RX = %r/\\u[A-F0-9]{4}|[A-Za-z0-9]/

js_rx = JsRegex.new /\p{L}/

raw = js_rx.source.gsub /\[|\]/, ''

s = StringScanner.new raw

def normalize_char char
  if char.start_with? '\\u00'
    %(\\x#{char.slice 4, char.length})
  else
    char
  end
end

chars = []

until s.eos?
  chars << (normalize_char s.scan CHAR_RX)
  if (s.peek 1) == '-'
    chars << s.get_byte
    chars << (normalize_char s.scan CHAR_RX)
  end
end

puts chars.join
```

**Comment by mojavelinux** [comment]
Here's the script I used to check for duplicates and gaps in the ranges.

```rb
require 'js_regex'
require 'strscan'

CHAR_RX = %r/\\u[A-F0-9]{4}|[A-Za-z]/

js_rx = JsRegex.new /\p{L}/

raw = js_rx.source.gsub /\[|\]/, ''

s = StringScanner.new raw

def normalize_char char
  if char.start_with? '\\u00'
    %(\\x#{char.slice 4, char.length})
  else
    char
  end
end

def resolve_glyph char
  if char.start_with? '\\u', '\\x'
    [((char.slice 2, char.length).to_i 16)].pack 'U'
  else
    char
  end
end

def resolve_char glyph
  if glyph.ascii_only?
    glyph
  else
    hex = sprintf('%X', glyph.unpack('U')[0])
    if hex.length < 3
      %(\\x#{hex})
    else
      %(\\u#{hex.rjust 4, '0'})
    end
  end
end

def next_glyph glyph
  [((sprintf '%X', glyph.unpack('U')[0] + 1).to_i 16)].pack 'U'
end

glyphs = []
until s.eos?
  glyphs << (curr_glyph = resolve_glyph s.scan CHAR_RX)
  if (s.peek 1) == '-'
    s.get_byte
    stop_glyph = resolve_glyph s.scan CHAR_RX
    until (curr_glyph = next_glyph curr_glyph) == stop_glyph
      glyphs << curr_glyph
    end
    glyphs << stop_glyph
  end
end

glyphs = glyphs.sort.uniq

chars = []

glyph = nil

while (glyph = glyphs.shift)
  chars << (resolve_char glyph)
  if (next_glyph glyph) == glyphs[0]
    glyph = glyphs.shift
    cnt = 0
    until (next_glyph glyph) != glyphs[0]
      cnt += 1
      glyph = glyphs.shift
    end
    chars << '-' if cnt > 0
    chars << (resolve_char glyph)
  end
end

puts chars.join
```

**Comment by mojavelinux** [comment]
I was using the js_regex gem. Unfortunately, I couldn't use it for all the ranges since it's missing Nl and Pc. But those were small enough to inspect manually. Perhaps we could contribute those ranges upstream so we can make use of this gem, which is actually quiet useful.

**Comment by mojavelinux** [comment]
Btw, here are the properties that Ruby recognizes w/ definitions. https://ruby-doc.org/core-2.4.1/Regexp.html#class-Regexp-label-Character+Properties

**Comment by mojavelinux** [comment]
I have an idea for how to shave off 1/3 the size of this string. If we use the 4-digit hex codes, then we can remove the repeating "\u" from the string and restore it using a gsub. Essentially, we can zip it.

**Comment by mojavelinux** [comment]
Here's a sample of that string:

```
0AA00B500BA00C0-00D600D8-00F600F8-02C1
```

Here's how that replacement might work:

```rb
gsub(/([A-F0-9]{4})(?:-([A-F0-9]{4}))?/) { '\\u' + $1 + ($2 ? %(-\\u#$2) : '') }
```

or

```rb
gsub(/([A-F0-9]{4})(?:-([A-F0-9]{4}))?/) { %(\\u#$1#{$2 && "-\\u#$2"}) }
```

**Comment by mojavelinux** [comment]
I'll update the PR with this proposal so we can see how much it improves the size. This may be the perfect compromise to having the codes in ascii yet still keeping the string reasonable in length.

**Comment by mojavelinux** [comment]
(of course, we'll need to add the 'A-Za-z' range manually, but that's pretty easy to see).

**Comment by mojavelinux** [comment]
Here's the script I used to create the packed ranges:

```rb
require 'js_regex'
require 'strscan'

CHAR_RX = %r/\\u[A-F0-9]{4}|\\x[A-F0-9]{2}|[A-Za-z0-9]/

js_rx = JsRegex.new Regexp.new %(\\p{#{ARGV[0] || 'L'}})

raw = js_rx.source.gsub /\[|\]/, ''

s = StringScanner.new raw

def normalize_char char
  if char.start_with? '\\u'
    char.slice 2, char.length
  elsif char.start_with? '\\x'
    '00' + (char.slice 2, char.length)
  else
    char
  end
end

chars = []

until s.eos?
  chars << (normalize_char s.scan CHAR_RX)
  if (s.peek 1) == '-'
    chars << s.get_byte
    chars << (normalize_char s.scan CHAR_RX)
  end
end

puts chars.join
```

**Comment by mojavelinux** [comment]
In the end, the change adds 1.1K, which is not horrible.

**Comment by Mogztter** [comment]
> In the end, the change adds 1.1K, which is not horrible.

Not bad!

> I have an idea for how to shave off 1/3 the size of this string. If we use the 4-digit hex codes, then we can remove the repeating "\u" from the string and restore it using a gsub. Essentially, we can zip it.

I'm not sure about this one, do you think it's worth it ? we are saving 2Ko, which is a good thing, but Opal is more than 700Ko 😝 
However the function `unpack_hex_range` is pretty simple so why not 🤔

**Comment by mojavelinux** [comment]
I actually find it easier to read without all the `\u`s in there.

**Comment by mojavelinux** [comment]
\o/

Btw, those changes I submitted got merged into the js_regex gem and released, so we can use that to recreate these ranges in the future. We may want to note that somewhere.

**Pull request merged**
