### PR TITLE
📑 Fix Timings#printReport type definition

### PR DESCRIPTION
**Pull request by bitPogo**
This patch makes all parameters of Timings#printReport optional.

See #1113

### CODE REVIEW

**Comment by Mogztter** [comment]
The build is failure is related to a change merged on asciidoctor/asciidoctor (master): https://github.com/asciidoctor/asciidoctor/pull/3835

Asciidoctor (master) does not force the "px" unit anymore so the assertion needs to be updated. I will take care of that in a separated pull request.

Could you please call `timings.printReport(memoryLogger)` and `timings.printReport()` in `tests.ts` to confirm that everything is working as expected?

**Comment by bitPogo** [comment]
Done

**Comment by Mogztter** [comment]
Looks good, I've rebased on master to make sure that everything is running fine.

**Review by Mogztter — APPROVED** [review]
Nice work, thanks :ok_hand:

**Pull request merged**
