### PR TITLE
add benchmark script

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by Mogztter** [comment]
LGTM but I will postpone the merge because I rewrote the "fetch sample data" task with Node in #167. I will move this method in a reusable module so we can use it with the benchmark script.

**Comment by mojavelinux** [comment]
No problem at all. In fact, I'm glad because I couldn't figure out how to download something in JavaScript (the script would terminate before the download even started...so I gave up and just did it in Ruby).

**Comment by Mogztter** [comment]
Follow-up #170

**Comment by mojavelinux** [comment]
Excellent. Let's close this one then. Nice work!

**Pull request closed without merging**
