### PR TITLE
Asciidoctor.js CLI

### PR DESCRIPTION
**Pull request by Mogztter**
Work in progress to discuss implementation detail

Ref #87

### CODE REVIEW

**Comment by Mogztter** [comment]
@mojavelinux @anthonny I'd appreciate review or feedback to get me going :smile:

**Comment by anthonny** [comment]
I'll make a review asap,
regarding the relative path, would it not make sense to create another project for the Cli ? like Grunt with grunt-cli ?
This project will have a dependency on asciidoctor.js
wdyt ?

**Comment by Mogztter** [comment]
> would it not make sense to create another project for the Cli ? like Grunt with grunt-cli ?

Yes why not. Actually I tried to add a dependency on `asciidoctor.js` for asciidoctor-cli (inside `asciidoctor.js`) but that's not working :smile: 

Maybe it's better to create another repository `asciidoctor-cli.js` because the release process is already quite complex in `asciidoctor.js` with one package...

**Comment by mojavelinux** [comment]
I support the idea of a separate repository as that embraces the convention created by grunt. Ideally, that repository name would be `asciidoctor.js-cli`.

**Comment by Mogztter** [comment]
I will create a new repository.

@mojavelinux are you sure about the name ? I think it's better to keep the suffix `.js` at the end of the name. Furthermore, the name of the npm package will be `asciidoctor-cli` (not `asciidoctor.js-cli`).

**Comment by mojavelinux** [comment]
Yep, asciidoctor-cli.js works for me.

I do think that the cli needs to be asciidoctor.js (or asciidoctorjs though). That makes it consistent with how we do it in AsciidoctorJ. Otherwise, the commandline can get mixed up with the Ruby-based one. wdyt?

**Comment by Mogztter** [comment]
> I do think that the cli needs to be asciidoctor.js (or asciidoctorjs though).

I agree

> That makes it consistent with how we do it in AsciidoctorJ. Otherwise, the commandline can get mixed up with the Ruby-based one. wdyt?

Hmm I see, now `asciidoctor.js-cli` makes sense.
I didn't know that AsciidoctorJ has a CLI, the name of the commandline is `asciidoctorj` ?

Our Bower and NPM packages are named `asciidoctor.js`. By convention we should add `-cli` suffix but we already have a suffix ! 
We could remove the `.js` suffix because Bower and NPM are JavaScript tools but the package name must contains the commandline name... Argh naming things! :smile: 

To be conservative I think that `asciidoctor.js-cli` for the package name and the repository name is a safe bet. The commandline should probably be `asciidoctorjs` (dot in commandline name is uncommon).

**Comment by mojavelinux** [comment]
> I didn't know that AsciidoctorJ has a CLI, the name of the commandline is asciidoctorj ?

Yes. You can try it out, btw, by using gvm. See http://gvmtool.net/

I'm okay with renaming the package to `asciidoctor` (and `asciidoctor-cli`) since it's understood that it's JavaScript. I agree with, and prefer, if we can name the commandline `asciidoctorjs`.

**Comment by Mogztter** [comment]
Closing in favor of: https://github.com/asciidoctor/asciidoctor-cli.js

**Comment by mojavelinux** [comment]
\o/

Nice job!

**Pull request closed without merging**
