### PR TITLE
resolves #282 add support for block filter in findBy API method

### LINKED ISSUE #282: API, AbstractBlock.find_by: allow to use a function as second attribute
Reference API: https://github.com/asciidoctor/asciidoctor/blob/7282b0a5864df2f587b5a5a8f3cda10f71ed5547/lib/asciidoctor/abstract_block.rb#L268

To pass a function, we need to use `Opal.block_send`:
```js
Opal.block_send(doc, 'find_by', toHash(selector), function (block) { block.$lineno() != Opal.nil })
```

Discussion: https://github.com/asciidoctor/atom-asciidoc-preview/pull/216#issuecomment-285847507

### PR DESCRIPTION
**Pull request by Mogztter**
Based on @mojavelinux work in #283

### CODE REVIEW

**Comment by mojavelinux** [comment]
Looks good to me.

For future reference, it's possible for you (as a maintainer) to force push to a PR branch, effectively replacing the content of that PR with any commits you push. In this case, you would have forced push to mojavelinux:issue-282 (assuming mojavelinux is the name of my remote).

**Comment by Mogztter** [comment]
I didn't try but did you check "Allow edits from maintainers." ?

**Comment by mojavelinux** [comment]
Yep. For me, I default to having it checked. I think once you check it, it remembers the setting.

**Comment by Mogztter** [comment]
force push seems to be not allowed:

```
git push mojavelinux issue-282 --force
```
```
To https://github.com/mojavelinux/asciidoctor.js
 ! [remote rejected] issue-282 -> issue-282 (permission denied)
error: failed to push some refs to 'https://github.com/mojavelinux/asciidoctor.js'
```

**Comment by mojavelinux** [comment]
Hmm. I wonder if it's because I'm also a maintainer. Strange. I'm still
learning the ropes of this feature.

**Pull request merged**
