### PR TITLE
use simpler mechanism to convert from Opal hash to JavaScript object

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Hmm, I just realized the IE 11 doesn't support Object.assign. Really? I suppose we could check ('assign' in Object) and then use the old school way as a fallback.

**Comment by mojavelinux** [comment]
It turns out Object.assign is slower. But what would be faster is `for..in`.

**Comment by mojavelinux** [comment]
Updated. There used to be a risk of doing `for..in`, but I think that's been resolved now, right?

(this would be the perfect use case for `for..of`, but IE 11 doesn't support that either.

**Comment by mojavelinux** [comment]
This build seems back to normal.

**Comment by mojavelinux** [comment]
I noticed you're already using Object.assign in this file. If you'd rather switch back to Object.assign, let me know.

**Comment by Mogztter** [comment]
> There used to be a risk of doing for..in

I'm just aware that `for .. in` is slower than a basic array loop (because it does more). What do you mean by "risk" ?

> I noticed you're already using Object.assign in this file. If you'd rather switch back to Object.assign, let me know.

Yes you can use `Object.assign`.
I need to document how to integrate Asciidoctor.js with old/deprecated browsers:

* https://polyfill.io/ 
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill

**Comment by mojavelinux** [comment]
Okay, let's go with Object.assign. I'll update.

**Comment by mojavelinux** [comment]
I think this is ready to go now.

**Comment by Mogztter** [comment]
The code looks nice 👍

**Pull request merged**
