### PR TITLE
Add CDNJS version badge in README.adoc

### PR DESCRIPTION
**Pull request by sufuf3**
This badge will show the version on CDNJS!

### CODE REVIEW

**Comment by mojavelinux** [comment]
Sounds like a great idea to me!

Could you move it up one line so it's after the npm badge? That way, the distribution badges are adjacent. Thanks!

**Comment by sufuf3** [comment]
@mojavelinux I moved it up one line. Now, the cdnjs badge is after the npm badge.
Thank you.

**Comment by Mogztter** [comment]
Perfect 💯 
Thank you 😄

**Comment by Mogztter** [comment]
And we are live! Thanks again @sufuf3 :wink:

**Comment by sufuf3** [comment]
Thanks a lot! :+1:

**Pull request merged**
