### PR TITLE
Add an example for slide backends

### PR DESCRIPTION
**Pull request by Mogztter**
Cancels and replaces #119 

```sh
 $ npm run examples
 $ http-server -a localhost # or python -m SimpleHTTPServer 8080
```

http://localhost:8080/build/examples/slide.html

### CODE REVIEW

**Comment by cmoulliard** [comment]
Did a quick test on my machine using this template (https://raw.githubusercontent.com/cmoulliard/hyla/2.0.x/lib/templates/sample/slideshow_revealjs.adoc) and I'm getting some jade warnings

screenshot 2016-09-02 11 22 16


Is it possible to include the name of the jade template where the error has been reported instead of getting this message `Warning: missing space before text for line 25 of jade file "undefined"` ?

**Comment by mojavelinux** [comment]
Am I correct that this will be superseded / reworked by the introduction of [asciidoctor-template.js](https://www.npmjs.com/package/asciidoctor-template.js)?

**Comment by Mogztter** [comment]
@mojavelinux Yes you are right.

**Comment by Mogztter** [comment]
This is not working yet on browsers (ie. examples) because of https://github.com/asciidoctor/asciidoctor-template.js/issues/2

**Comment by Mogztter** [comment]
The `npm run examples` now output:

```
In order to visualize the result, a local HTTP server must be started within the root of this project otherwise you will have cross-origin issues.
For this purpose, you can run the following command to start a HTTP server locally: npm run server

>> You can now open:
 - build/examples/asciidoctor_example.html
 - build/examples/userguide_test.html
 - build/examples/slide.html
```

The following command will start a local HTTP server (using `http-server` node module as suggested by @cmoulliard)

```
npm run server
```

**Comment by Mogztter** [comment]
> I'm getting some jade warnings

@cmoulliard fixed in https://github.com/asciidoctor/asciidoctor-reveal.js/pull/107

**Pull request merged**
