### PR TITLE
Set environment variable cross-platform compatible

### PR DESCRIPTION
**Pull request by rahmanusta**

### CODE REVIEW

**Comment by mojavelinux** [comment]
More context here: https://www.npmjs.com/package/cross-env

**Comment by Mogztter** [comment]
We do need to have a cross environnent compatible build but cross-env has two dependencies which have more dependencies which have... (welcome to the Node.js world).
I think we can find a simpler solution that doesn't require a library.
I will do some testing on Windows to better understand this issue.

One idea is to use program arguments instead of environment variables since we have full control over the build.

Wdyt?

**Comment by rahmanusta** [comment]
> One idea is to use program arguments instead of environment variables since we have full control over the build.

I agree with you, we can use program arguments instead of environment variables with no dependency.

**Comment by Mogztter** [comment]
Merged in 9fdb21c5315718b7facc867229e32e4c23beab24

**Comment by rahmanusta** [comment]
Thank you @Mogztter !

**Pull request closed without merging**
