### PR TITLE
resolves #321, API: Postprocessor extension

### LINKED ISSUE #321: Map the API needed to write a postprocessor extension
Map the APIs needed to write a postprocessor extension.

It should be possible to write the following (pseudo-code):

```ruby
Opal.Asciidoctor.$$scope.Extensions.register(function() {
  var self = this;
  this.postprocessor(function() {
    self.process(function(doc, output) {
      return output.replace(/foo/, 'bar');
    });
  });
});
```

### PR DESCRIPTION
**Pull request by Mogztter**
resolves #321

### CODE REVIEW

**Comment by mojavelinux** [comment]
Looks good, except the title of the PR doesn't match the code.

**Comment by Mogztter** [comment]
Oups and the commit message is wrong :(
Thanks for your review.

**Comment by Mogztter** [comment]
Fixed!

**Comment by mojavelinux** [comment]
Nice! Good job!

**Pull request merged**
