### PR TITLE
📝 Improve support matrix readability

### PR DESCRIPTION
**Pull request by Mogztter**
| Current | After |
| -- | -- |
|current |compat-less-monospaced

### CODE REVIEW

**Comment by mojavelinux** [comment]
That's definitely a much tighter layout.

You are missing two escapes for raw.com.

I don't think the column should be named MRI. It should just be named Ruby.

**Comment by mojavelinux** [comment]
You only need the AsciiDoc table cell if the cell has blocks. So I think the colspan rows can just be default table cells. If you need a hard line break, I would use the trailing + instead.

**Comment by mojavelinux** [comment]
I wonder if the title of the first column should be File / Message. Then it's clear what the colspan rows are about.

**Comment by Mogztter** [comment]
> You only need the AsciiDoc table cell if the cell has blocks. So I think the colspan rows can just be default table cells. If you need a hard line break, I would use the trailing + instead.

True, but the first cell is using a monospaced style so I'm using the inline AsciiDoc cell style to override it.
Alternatively, I could remove the monospaced style and apply on every path/file... :thinking: 

> You are missing two escapes for raw.com.

Can't see it :eyes: 

> I don't think the column should be named MRI. It should just be named Ruby.

:+1: 

> I wonder if the title of the first column should be File / Message. Then it's clear what the colspan rows are about.

:+1:

**Comment by mojavelinux** [comment]
> True, but the first cell is using a monospaced style so I'm using the inline AsciiDoc cell style to override it.

You can use the "d" style to return to the default/normal cell style.

**Comment by mojavelinux** [comment]
> > You are missing two escapes for raw.com.

> Can't see it

Nevermind, it must just be GitHub messing up. I don't see it either.

**Comment by mojavelinux** [comment]
I have one other idea for this table. The messages line still seems hard to map visually. One idea would be to use the first column (or two) for the header, then put the messages across the remaining columns.

```
| File              | Base dir     | Browser | Node.js | Ruby
| path/to/file.adoc | file:///root | 👌      | 👌       | ❌
                          Messages | Ruby: The resolved path is /root/file:/root/path/to/file.adoc.
```

(Disclaimer: I am not a table specialist, so this may be off base)

**Comment by Mogztter** [comment]
> I have one other idea for this table. The messages line still seems hard to map visually. One idea would be to use the first column (or two) for the header, then put the messages across the remaining columns.


What about a collapsible block?

```
.Messages
[%collapsible]
====
Ruby: The resolved path is [.path]_/root/file:/root/path/to/file.adoc_.
====
```

**Comment by mojavelinux** [comment]
Perhaps, though I'd like to see the simpler approach first. I would also include that row even if there are no messages. Just write "Not applicable". That way, the table looks uniform and we can style the rows using even/odd highlighting if necessary.

**Comment by Mogztter** [comment]
> I would also include that row even if there are no messages. Just write "Not applicable"

That's a good idea :+1: 

> One idea would be to use the first column (or two) for the header, then put the messages across the remaining columns.

I tried but it does not look great. Also I'm trying to avoid using bold/strong in the cells otherwise the table header does not stand out visually anymore.

**Comment by mojavelinux** [comment]
How did you do the expand? Is that extra JavaScript?

**Comment by Mogztter** [comment]
> How did you do the expand? Is that extra JavaScript?

Yes! As requested, I added a unique id and the table structure is uniform so we can use even/odd and target the next row to show/hide details using JavaScript. Of course, styling should be done using CSS.

**Comment by Mogztter** [comment]
I will merge this pull request as it already greatly improves readability even if we don't add some JavaScript to hide/show the reason.

**Pull request merged**
