### PR TITLE
fix toHash logic

### PR DESCRIPTION
**Pull request by mojavelinux**
- properly detect Opal hash
- consolidate impl to a single line
- use better variable name in fromHash

### CODE REVIEW

**Comment by mojavelinux** [comment]
The existing implementation was not properly detecting an Opal hash. As a result, it was always converting to a hash, hence performing redundant logic.

**Comment by Mogztter** [comment]
> The existing implementation was not properly detecting an Opal hash. As a result, it was always converting to a hash, hence performing redundant logic.

Nice catch! I'm wondering if it's possible to provide a test case... :thinking:

**Comment by mojavelinux** [comment]
I thought about that, but I can't see a way unless we exposed the function.

**Comment by mojavelinux** [comment]
In a way, it's already tested in that the tests do use both cases. What isn't tested is redundant work, but I don't actually think that needs to be tested. As long as the behavior is correct, it's "correct".

**Comment by Mogztter** [comment]
I agree!

**Pull request merged**
