### PR TITLE
Add missing pictures. Fix #124

### PR DESCRIPTION
**Pull request by cmoulliard**
- Add the 2 missing png files

### CODE REVIEW

**Comment by Mogztter** [comment]
These images are used in https://github.com/asciidoctor/asciidoctor.js/blob/master/CONTRIBUTING-CODE.adoc and should be copied in the examples directory: https://github.com/asciidoctor/asciidoctor.js/blob/master/npm/builder.js#L468

Do you have see an error ?

**Comment by cmoulliard** [comment]
The images are referred within the adoc file so asciidoctor complaints during the rendering

**Comment by Mogztter** [comment]
OK thanks for the clarification, I will try to find out why images are not
copied.

Le 1 sept. 2016 8:15 PM, "Charles Moulliard" <notifications@github.com> a
écrit :

**Comment by mojavelinux** [comment]
Correct, the README no longer has images, so they shouldn't be needed for the example. Of course, if images are added to the README, then they would be needed. In that case, the script should copy them to the output. We should not be duplicating files within the git repository itself.

**Comment by Mogztter** [comment]
I don't see any error, could you please describe what commands you are using ? Are you up-to-date ?

>  Correct, the README no longer has images, so they shouldn't be needed for the example.

I can confirm that these images are no longer required, I will update the script.

**Comment by cmoulliard** [comment]
You are right. Sorry for my mistake. This error is not there.

```
node npm/examples.js 
Object tainting is not supported by Opal

examples

clean
 - delete build directory

download dependencies
get https://codeload.github.com/asciidoctor/asciidoctor/tar.gz/v1.5.4 to build/asciidoctor.tar.gz
get https://codeload.github.com/asciidoctor/asciidoctor-latex/tar.gz/0.2 to build/asciidoctor-latex.tar.gz
get https://codeload.github.com/threedaymonk/htmlentities/tar.gz/v4.3.3 to build/htmlentities.tar.gz

compile latex
 - compile asciidoctor-latex

compile core lib
 - compile asciidoctor/converter/docbook5
 - compile asciidoctor/converter/docbook45
 - compile asciidoctor/extensions
 - compile asciidoctor
`
compile extensions-lab lib
 - compile chrome-inline-macro
 - compile man-inline-macro
 - compile emoji-inline-macro
 - compile chart-block-macro

copy resources
 - copy asciidoctor.css

concat
 - npm core
 - npm core.min
 - npm extensions
 - npm docbook
 - Bower core + extensions
 - Bower docbook
 - Bower all
MINIFY environment variable is not defined, skipping "minify" task

>> Done in 35s

compile examples
 - compile examples/asciidoctor_example.rb
 - compile examples/userguide_test.rb

copy resources to build/examples/
copy examples/asciidoctor_example.html to build/examples/asciidoctor_example.html
copy examples/userguide_test.html to build/examples/userguide_test.html
copy examples/asciidoctor.css to build/examples/asciidoctor.css
copy README.adoc to build/examples/README.adoc

copy images to build/examples/images/
copy error-in-chrome-console.png to build/examples/images/error-in-chrome-console.png
copy error-in-javascript-debugger.png to build/examples/images/error-in-javascript-debugger.png

download sample data from AsciiDoc repository
get https://raw.githubusercontent.com/asciidoc/asciidoc/d43faae38c4a8bf366dcba545971da99f2b2d625/doc/asciidoc.txt to build/examples/userguide.adoc
get https://raw.githubusercontent.com/asciidoc/asciidoc/d43faae38c4a8bf366dcba545971da99f2b2d625/doc/customers.csv to build/examples/customers.csv

>> You can now open build/examples/asciidoctor_example.html and build/examples/userguide_test.html
```

**Comment by Mogztter** [comment]
No problem, we've fixed a mistake in the process :wink: 
Can I close this pull request ?

**Pull request closed without merging**
