### PR TITLE
make improvements to public extensions API

### PR DESCRIPTION
**Pull request by mojavelinux**
- add methods for registering a custom block
- add a test for a custom block
- rename createBlock to toBlock
- calculate arity dynamically
- add method to create an inline (node)
- change smiley extension to create inline quoted node
- convert function to Ruby block where missing

### CODE REVIEW

**Comment by mojavelinux** [comment]
#291 needs to be merged in order for the tests to pass (or we need to specify to build against v1.5.5).

**Comment by mojavelinux** [comment]
I got more enhancements riding on the coat tails of this PR (i.e., coming after).

**Comment by Mogztter** [comment]
This is looking good! Thanks :+1: 
I've just merged #291

**Comment by mojavelinux** [comment]
PR updated!

**Comment by Mogztter** [comment]
Nice improvements :wink: 
Once the API is stable, we should write documentation on how to write extension in JavaScript.

**Comment by mojavelinux** [comment]
> Once the API is stable, we should write documentation on how to write extension in JavaScript.

I'd be glad to help with that. Perhaps open an issue with what you're looking for and assign it to me?

**Comment by mojavelinux** [comment]
Okay, next PR on the way!

**Comment by Mogztter** [comment]
> I'd be glad to help with that. Perhaps open an issue with what you're looking for and assign it to me?

https://github.com/asciidoctor/asciidoctor.js/issues/76

**Pull request merged**
