### PR TITLE
Upgrade to Opal v0.8.0

### LINKED ISSUE #115: Upgrade to Opal 0.8.x
Cross compilation is working fine but I get the following error at runtime:

```
TypeError: asciidoctor: FAILED: <stdin>: Failed to parse source, no implicit conversion of NilClass into String
    at OpalClass.$new (opal.js:3361)
    at module_constructor.<anonymous> (opal.js:3037)
    at module_constructor.self.$$proto.$load (asciidoctor.js:13160)
    at updateBody (renderer.js:72)
    at Object.callback (renderer.js:58)
    at safeCallbackApply (VM31121 extensions::sendRequest:21)
    at handleResponse (VM31121 extensions::sendRequest:72)
```

I opened an issue https://github.com/opal/opal/issues/904

### PR DESCRIPTION
**Pull request by Mogztter**
Resolves #115

### CODE REVIEW

**Comment by Mogztter** [comment]
I think we are good to go. I've:
 
 * Removed `hash2` by `hash`
 * Automatically required Asciidoctor modules
 * Added an user manual to document how to disable auto-require

@mojavelinux @anthonny Wdyt ?

**Comment by Mogztter** [comment]
@mojavelinux @anthonny Is this look good to you ? is this the right time to merge this pull request ?

**Comment by mojavelinux** [comment]
:+1: Sorry for letting this linger. You read my mind :)

**Comment by Mogztter** [comment]
No worries, I just want to move things forward if that's OK with you :smile:

**Comment by Mogztter** [comment]
I've caught a regression with attributes.

Given:
```javascript
var options = Opal.hash({'attributes': 'icons=font something!'});
var doc = Opal.Asciidoctor.$load(data, options);
console.log(doc.attributes);
```

Then, output contains:
```
{"icons"=>"font$1"}
```

Given:
```javascript
var options = Opal.hash({'attributes': ['icons=font', 'something!']});
var doc = Opal.Asciidoctor.$load(data, options);
console.log(doc.attributes);
```

Then, output contains:
```
{"icons"=>"font"}
```

I don't know why there's a trailing `$1`... @mojavelinux any idea ?

**Comment by mojavelinux** [comment]
>  I just want to move things forward if that's OK with you 

Of course! Thank you.

> I don't know why there's a trailing $1... @mojavelinux any idea ?

Very likely a change in back-reference syntax in Opal. We may have been relying on a bug. It will require some investigation. Either Opal is failing to replace it, or for some reason now requires `\\1` instead (or something different).

**Pull request merged**
