### PR TITLE
🐛 resolves #1493 fix global variable leak

### LINKED ISSUE #1493: Global variables leak when assigning variables that are not declared
We need to backport https://github.com/asciidoctor/asciidoctor.js/commit/28d3fad81ff8bf663cb97ae54c9d7997f8563d90 to the v2.2.x branch.

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Looks like we need to update the build to point to main instead of master.

**Comment by mojavelinux** [comment]
I'll rebase once #1495 is merged.

**Comment by Mogztter** [comment]
> Looks like we need to update the build to point to main instead of master.

Thanks for taking care of it 💚 

> I'll rebase once #1495 is merged.

I just merged #1495 !

**Comment by mojavelinux** [comment]
Thanks! Rebase complete.

**Pull request merged**
