### PR TITLE
resolves #367 replace . with [\S\s] in regexp

### LINKED ISSUE #367: Processor fails to convert document containing a certain sequence of characters
Asciidoctor.js 1.5.6-preview.3 fails to convert the following document:

```
const asciidoctor = require('asciidoctor')()
asciidoctor.convert('* a\n* \u2028b')
```

The line separator character (`\u2028`) is causing Asciidoctor.js to go into an infinite loop. Asciidoctor Ruby converts this document without issue.

### PR DESCRIPTION
**Pull request by mojavelinux**
Fixes an infinite loop when a sibling list item contains the line separator character.

### CODE REVIEW

**Comment by mojavelinux** [comment]
I hate to have to solve it this way, but I'm not sure what else we can do without a change to core. It's really annoying that the JavaScript `.` does not match the same as in Ruby.

**Comment by Mogztter** [comment]
I think this fix could be integrated in Opal. If MRI and Opal behave differently then it should be fixed in Opal: https://github.com/opal/opal/blob/8f182584aa6e2a21214ac3e43cae1c0c8efbbc4d/lib/opal/nodes/literal.rb#L177

Do you have a simple test case with a condition that's true with MRI but false with Opal ?

**Comment by Mogztter** [comment]
And in the meantime we should definitely merge this fix 😉 

Did you find out why it's working with preview-2 but not with preview-3 ? Did we change the RegExp in core to use dots ? Or is it a regression in Opal/Asciidoctor.js ?

**Comment by mojavelinux** [comment]
There's a test in there that demonstrates what it's fixing. However, I'd like to update it to add all the scenarios.

The detailed explanation for why this started failing can be found in the issue #367.

I'm not sure this is something we want Opal to fix, because it's one of many differences in the regexp engine. The more I think about it, the more I realize that it needs to be fixed in our regexp layer. And I actually have another way of fixing it. (One new idea I had is to make a special AnyListRx for Opal that matches like the other ListRx expressions...in other words, solve the other side of the mismatch).

**Comment by mojavelinux** [comment]
We should hold off on the merge until we've settled on the strategy for fixing. I just wanted to get the PR out there so that we have something to discuss.

**Comment by Mogztter** [comment]
Build is failing on version 1.5.5 because, the list is not encapsulated in a `<div class="paragraph">`.
I'm planning to drop 1.5.5 support on master: https://github.com/asciidoctor/asciidoctor.js/pull/376

> We should hold off on the merge until we've settled on the strategy for fixing. I just wanted to get the PR out there so that we have something to discuss.

The fix looks fine to me

> However, I'd like to update it to add all the scenarios.

Could you please elaborate this point ? Can I help on this task ?

**Comment by Mogztter** [comment]
I've rebased your work on top of master, now the build is green :Tara:

**Comment by mojavelinux** [comment]
Great!

I still need to add the additional scenarios. I've been extremely busy these last few weeks though, so I've been slow to get to it. But what I'm working on is wrapping up this week.

**Comment by mojavelinux** [comment]
Well, that month flew by. I'm back looking at this today.

**Comment by mojavelinux** [comment]
PR updated. I'll comment in issue w/ details.

**Comment by mojavelinux** [comment]
@Mogztter wdyt?

**Comment by Mogztter** [comment]
@mojavelinux It looks good to me, I have just one remark on the regular expression (ie. should we use `^\n` or `\S\s`): https://github.com/asciidoctor/asciidoctor.js/issues/367#issuecomment-333819404 

As far as I understand you are leaning toward `^\n` but you also mentioned that we are dealing with single line expressions so we could use `\S\s` to remove the negation ?

**Comment by mojavelinux** [comment]
I'm a bit uncertain about what the right choice is. Technically, `\S\s` would be perfectly safe as we are dealing with single-line expressions. The reason I chose `[^\n]` is because that more closely aligns with the intention of the `.` character. If we have the right tests, it shouldn't matter which one we choose because we know we can prove it works.

**Comment by Mogztter** [comment]
> The reason I chose [^\n] is because that more closely aligns with the intention of the . character. 

You are right:

> /./ - Any character except a newline.

https://ruby-doc.org/core-2.1.1/Regexp.html#class-Regexp-label-Character+Classes

I was trying to avoid negation but in this case it make perfect sense, so :+1:

**Comment by mojavelinux** [comment]
Let's go for it. Merge at will.

**Comment by Mogztter** [comment]
Done 🍻 
Thanks Dan 😃

**Pull request merged**
